def tampil_visual():
    print("\n=== Visual Habit Growth ===")
    print()
    print("🎮 Habit Quest")
    print()
    print("[🌱] Rookie Survivor      - 1 Hari")
    print("[🌿] Consistent Explorer  - 7 Hari")
    print("[🌳] Habit Guardian       - 30 Hari")
    print("[🌲] Master of Control    - 60 Hari")
    print("[🏆] Re:Me Legend         - 100 Hari")
    print()
    print("Unlock achievement baru dengan menjaga streak harian!")